import { describe, expect, it } from "vitest";
import {
  CHUNK_EMBEDDING_RESULT_STATUSES,
  EMBEDDING_CACHE_ENTRY_STATUSES,
  EMBEDDING_CACHE_LOOKUP_STATUSES,
  EMBEDDING_ERROR_CODES,
  EMBEDDING_EVENT_NAMES,
  EMBEDDING_PROVIDER_CAPABILITIES,
  EMBEDDING_PROVIDER_STABILITY_STATUSES,
  EMBEDDING_RESULT_STATUSES,
  EMBEDDING_RESPONSE_STATUSES,
  EMBEDDING_VALIDATION_ISSUE_CODES,
  EMBEDDING_VALUE_KINDS,
  embeddingFixtureCacheEntry,
  embeddingFixtureRequestedEvent,
  embeddingFixtureResult
} from "../index.js";

describe("embedding contract stability", () => {
  it("locks public vocabulary constants", () => {
    expect(EMBEDDING_VALUE_KINDS).toEqual(["text", "chunk"]);
    expect(EMBEDDING_PROVIDER_STABILITY_STATUSES).toEqual([
      "experimental",
      "stable",
      "deprecated"
    ]);
    expect(EMBEDDING_PROVIDER_CAPABILITIES).toEqual([
      "single-input",
      "batch-input",
      "chunk-input",
      "usage-metadata",
      "dimension-selection"
    ]);
    expect(EMBEDDING_RESPONSE_STATUSES).toEqual([
      "success",
      "partial-success",
      "failure"
    ]);
    expect(CHUNK_EMBEDDING_RESULT_STATUSES).toEqual([
      "success",
      "partial-success",
      "validation-failure",
      "provider-failure"
    ]);
    expect(EMBEDDING_VALIDATION_ISSUE_CODES).toEqual([
      "missing-input",
      "empty-text",
      "invalid-dimensions",
      "unsupported-provider-capability",
      "unsupported-model",
      "input-too-large",
      "invalid-chunk-reference",
      "unsafe-metadata"
    ]);
    expect(EMBEDDING_CACHE_ENTRY_STATUSES).toEqual([
      "fresh",
      "stale",
      "expired"
    ]);
    expect(EMBEDDING_CACHE_LOOKUP_STATUSES).toEqual([
      "hit",
      "miss",
      "stale",
      "failure"
    ]);
    expect(EMBEDDING_RESULT_STATUSES).toEqual([
      "success",
      "partial-success",
      "validation-failure",
      "provider-failure",
      "cache-hit",
      "cache-miss",
      "skipped"
    ]);
    expect(EMBEDDING_ERROR_CODES).toEqual([
      "EMBEDDING_VALIDATION_FAILED",
      "EMBEDDING_PROVIDER_FAILED",
      "EMBEDDING_CACHE_FAILED",
      "EMBEDDING_EVENT_FAILED",
      "EMBEDDING_INTERNAL_FAILURE"
    ]);
    expect(EMBEDDING_EVENT_NAMES).toEqual([
      "embedding.requested",
      "embedding.validated",
      "embedding.generated",
      "embedding.failed",
      "embedding.cached",
      "embedding.skipped"
    ]);
  });

  it("locks representative result, cache, and event shapes", () => {
    expect(Object.keys(embeddingFixtureResult).sort()).toEqual([
      "cacheStatus",
      "embeddings",
      "issues",
      "ok",
      "safeMetadata",
      "status"
    ]);
    expect(Object.keys(embeddingFixtureCacheEntry).sort()).toEqual([
      "embedding",
      "key",
      "metadata",
      "status",
      "storedAt"
    ]);
    expect(Object.keys(embeddingFixtureRequestedEvent.metadata).sort()).toEqual([
      "category",
      "correlationId",
      "eventId",
      "eventName",
      "requestId",
      "source",
      "timestamp",
      "version"
    ]);
  });
});
